### ISSUE TITLE
How can i use this with an item with a custom model data ?

### ISSUE THREAD

**Issue by ODHG1** [ICY105/PlayerAction#1]
It's a diamond sword with a custom model data being 69, i'd like to use the left click detection (function #player_action:v1/left_click)

**Comment by ICY105** [comment]
Add the nbt tag that activates it, ie. `diamond_sword{CustomModelData:69,player_action:{click_detection:1b}}`
Note this works by hovering an interaction entity in front of the player, so they won't be able to attack normally.
